INFO 2023-10-11 23:43:11,123 autoreload 21028 17176 Watching for file changes with StatReloader
INFO 2023-10-11 23:43:28,331 autoreload 21028 17176 K:\django_lessons_gb\home_work\hw_one\myproject\myproject\settings.py changed, reloading.
INFO 2023-10-11 23:43:29,614 autoreload 1524 21384 Watching for file changes with StatReloader
INFO 2023-10-11 23:43:36,314 autoreload 1524 21384 K:\django_lessons_gb\home_work\hw_one\myproject\myproject\settings.py changed, reloading.
INFO 2023-10-11 23:43:37,486 autoreload 3300 7208 Watching for file changes with StatReloader
INFO 2023-10-11 23:43:44,287 basehttp 3300 12440 "GET / HTTP/1.1" 200 125
INFO 2023-10-11 23:43:50,170 basehttp 3300 12440 "GET /about/ HTTP/1.1" 200 242
INFO 2023-10-18 10:15:57,026 autoreload 14476 14460 Watching for file changes with StatReloader
INFO 2023-10-18 10:15:58,849 basehttp 14476 15976 "GET / HTTP/1.1" 200 125
WARNING 2023-10-18 10:15:58,934 log 14476 15976 Not Found: /favicon.ico
WARNING 2023-10-18 10:15:58,935 basehttp 14476 15976 "GET /favicon.ico HTTP/1.1" 404 2648
INFO 2023-10-18 10:16:30,575 autoreload 14476 14460 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\urls.py changed, reloading.
INFO 2023-10-18 10:16:31,725 autoreload 14776 13760 Watching for file changes with StatReloader
INFO 2023-10-18 10:16:40,792 basehttp 14776 12496 "GET /orders_products/1/3 HTTP/1.1" 301 0
ERROR 2023-10-18 10:16:40,836 log 14776 12496 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\list.py", line 35, in get_queryset
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: ProductsOrders is missing a QuerySet. Define ProductsOrders.model, ProductsOrders.queryset, or override ProductsOrders.get_queryset().
ERROR 2023-10-18 10:16:40,839 basehttp 14776 12496 "GET /orders_products/1/3/ HTTP/1.1" 500 80659
INFO 2023-10-18 10:17:58,809 autoreload 14776 13760 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 10:17:59,950 autoreload 15052 2112 Watching for file changes with StatReloader
ERROR 2023-10-18 10:18:00,693 log 15052 14468 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 15: 'endblock', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
ERROR 2023-10-18 10:18:00,714 basehttp 15052 14468 "GET /orders_products/1/3/ HTTP/1.1" 500 171943
ERROR 2023-10-18 10:19:30,511 log 15052 14468 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 15: 'endblock', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
ERROR 2023-10-18 10:19:30,786 basehttp 15052 14468 "GET /orders_products/1/3/ HTTP/1.1" 500 172411
ERROR 2023-10-18 10:19:44,049 log 15052 14468 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 15: 'endblock', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
ERROR 2023-10-18 10:19:44,053 basehttp 15052 14468 "GET /orders_products/1/3/ HTTP/1.1" 500 172589
INFO 2023-10-18 10:19:56,868 basehttp 15052 14468 "GET /orders_products/1/3/ HTTP/1.1" 200 193
INFO 2023-10-18 10:23:38,124 autoreload 15052 2112 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 10:23:39,559 autoreload 16304 16364 Watching for file changes with StatReloader
ERROR 2023-10-18 10:23:42,922 log 16304 5880 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 522, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 15: 'endblock', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
ERROR 2023-10-18 10:23:42,928 basehttp 16304 5880 "GET /orders_products/1/3/ HTTP/1.1" 500 172013
INFO 2023-10-18 10:25:55,658 autoreload 16304 16364 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 10:25:57,060 autoreload 15280 15368 Watching for file changes with StatReloader
INFO 2023-10-18 10:25:57,342 basehttp 15280 10692 "GET /orders_products/1/3/ HTTP/1.1" 200 251
ERROR 2023-10-18 10:26:29,044 log 15280 10692 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '()' from 'context.items()'
ERROR 2023-10-18 10:26:29,050 basehttp 15280 10692 "GET /orders_products/1/3/ HTTP/1.1" 500 154459
INFO 2023-10-18 10:26:49,602 basehttp 15280 10692 "GET /orders_products/1/3/ HTTP/1.1" 200 198
INFO 2023-10-18 10:26:51,399 basehttp 15280 10692 "GET /orders_products/1/3/ HTTP/1.1" 200 198
INFO 2023-10-18 10:27:24,840 autoreload 15280 15368 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 10:27:25,936 autoreload 1344 15712 Watching for file changes with StatReloader
ERROR 2023-10-18 10:27:26,182 log 1344 13764 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 59, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\context.py", line 268, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than builtin_function_or_method.
ERROR 2023-10-18 10:27:26,185 basehttp 1344 13764 "GET /orders_products/1/3/ HTTP/1.1" 500 79214
ERROR 2023-10-18 10:27:28,214 log 1344 13764 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 59, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\context.py", line 268, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than builtin_function_or_method.
ERROR 2023-10-18 10:27:28,215 basehttp 1344 13764 "GET /orders_products/1/3/ HTTP/1.1" 500 79214
ERROR 2023-10-18 10:29:37,786 log 1344 13764 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 59, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\context.py", line 268, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than builtin_function_or_method.
ERROR 2023-10-18 10:29:37,788 basehttp 1344 13764 "GET /orders_products/1/3/ HTTP/1.1" 500 79214
ERROR 2023-10-18 10:29:38,613 log 1344 13764 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 59, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\context.py", line 268, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than builtin_function_or_method.
ERROR 2023-10-18 10:29:38,615 basehttp 1344 13764 "GET /orders_products/1/3/ HTTP/1.1" 500 79214
INFO 2023-10-18 10:29:40,208 autoreload 1344 15712 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 10:29:41,561 autoreload 16324 16052 Watching for file changes with StatReloader
ERROR 2023-10-18 10:29:44,110 log 16324 5660 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 59, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\context.py", line 268, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than builtin_function_or_method.
ERROR 2023-10-18 10:29:44,115 basehttp 16324 5660 "GET /orders_products/1/3/ HTTP/1.1" 500 79214
INFO 2023-10-18 10:29:53,008 autoreload 16324 16052 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 10:29:54,227 autoreload 8144 15692 Watching for file changes with StatReloader
ERROR 2023-10-18 10:29:54,999 log 8144 16244 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 59, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\context.py", line 268, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than dict_items.
ERROR 2023-10-18 10:29:55,002 basehttp 8144 16244 "GET /orders_products/1/3/ HTTP/1.1" 500 79384
ERROR 2023-10-18 10:29:55,751 log 8144 16244 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 59, in render
    context = make_context(context, request, autoescape=self.backend.engine.autoescape)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\context.py", line 268, in make_context
    raise TypeError('context must be a dict rather than %s.' % context.__class__.__name__)
TypeError: context must be a dict rather than dict_items.
ERROR 2023-10-18 10:29:55,753 basehttp 8144 16244 "GET /orders_products/1/3/ HTTP/1.1" 500 79384
INFO 2023-10-18 10:30:19,896 autoreload 8144 15692 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 10:30:21,459 autoreload 13748 16032 Watching for file changes with StatReloader
INFO 2023-10-18 10:30:22,457 basehttp 13748 16168 "GET /orders_products/1/3/ HTTP/1.1" 200 198
ERROR 2023-10-18 10:30:30,680 log 13748 16168 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '()' from 'orders_products.items()'
ERROR 2023-10-18 10:30:30,687 basehttp 13748 16168 "GET /orders_products/1/3/ HTTP/1.1" 500 154579
ERROR 2023-10-18 10:30:59,922 log 13748 16168 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '()' from 'orders_products.items()'
ERROR 2023-10-18 10:30:59,928 basehttp 13748 16168 "GET /orders_products/1/3/ HTTP/1.1" 500 154579
INFO 2023-10-18 10:30:59,975 autoreload 13748 16032 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 10:31:01,326 autoreload 15104 1412 Watching for file changes with StatReloader
ERROR 2023-10-18 10:31:01,573 log 15104 5416 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '()' from 'orders_products.items()'
ERROR 2023-10-18 10:31:01,581 basehttp 15104 5416 "GET /orders_products/1/3/ HTTP/1.1" 500 154579
ERROR 2023-10-18 10:31:03,380 log 15104 5416 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '()' from 'orders_products.items()'
ERROR 2023-10-18 10:31:03,384 basehttp 15104 5416 "GET /orders_products/1/3/ HTTP/1.1" 500 154579
ERROR 2023-10-18 10:31:04,379 log 15104 5416 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '()' from 'orders_products.items()'
ERROR 2023-10-18 10:31:04,382 basehttp 15104 5416 "GET /orders_products/1/3/ HTTP/1.1" 500 154579
INFO 2023-10-18 10:32:12,027 basehttp 15104 5416 "GET /orders_products/1/3/ HTTP/1.1" 200 208
INFO 2023-10-18 10:33:33,337 basehttp 15104 5416 "GET /orders_products/1/3/ HTTP/1.1" 200 208
INFO 2023-10-18 10:33:34,915 basehttp 15104 5416 "GET /orders_products/1/3/ HTTP/1.1" 200 208
INFO 2023-10-18 10:33:35,996 autoreload 15104 1412 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 10:33:37,266 autoreload 14296 6344 Watching for file changes with StatReloader
ERROR 2023-10-18 10:33:39,853 log 14296 12128 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 41, in get_context_data
    print(**kwargs)
TypeError: 'year' is an invalid keyword argument for print()
ERROR 2023-10-18 10:33:39,855 basehttp 14296 12128 "GET /orders_products/1/3/ HTTP/1.1" 500 80959
INFO 2023-10-18 10:33:52,656 autoreload 14296 6344 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 10:33:54,085 autoreload 14916 4528 Watching for file changes with StatReloader
INFO 2023-10-18 10:33:54,356 basehttp 14916 1976 "GET /orders_products/1/3/ HTTP/1.1" 200 208
INFO 2023-10-18 11:24:54,428 autoreload 14888 5248 Watching for file changes with StatReloader
INFO 2023-10-18 11:24:55,142 basehttp 14888 16032 "GET /orders_products/1/3/ HTTP/1.1" 200 235
INFO 2023-10-18 11:24:56,869 basehttp 14888 16032 "GET /orders_products/1/3/ HTTP/1.1" 200 235
ERROR 2023-10-18 11:25:06,180 log 14888 16032 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'orders_week[0]'
ERROR 2023-10-18 11:25:06,185 basehttp 14888 16032 "GET /orders_products/1/3/ HTTP/1.1" 500 154452
ERROR 2023-10-18 11:25:07,517 log 14888 16032 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'orders_week[0]'
ERROR 2023-10-18 11:25:07,521 basehttp 14888 16032 "GET /orders_products/1/3/ HTTP/1.1" 500 154452
INFO 2023-10-18 11:25:21,195 basehttp 14888 16032 "GET /orders_products/1/3/ HTTP/1.1" 200 235
INFO 2023-10-18 11:25:52,086 autoreload 14888 5248 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 11:25:53,226 autoreload 1112 16780 Watching for file changes with StatReloader
INFO 2023-10-18 11:30:12,419 autoreload 1112 16780 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 11:30:13,560 autoreload 17132 16428 Watching for file changes with StatReloader
ERROR 2023-10-18 11:30:15,406 log 17132 1372 Internal Server Error: /orders_products/1/3/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp/orders_product.html
ERROR 2023-10-18 11:30:15,408 basehttp 17132 1372 "GET /orders_products/1/3/ HTTP/1.1" 500 80924
INFO 2023-10-18 11:30:44,557 autoreload 17132 16428 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 11:30:45,709 autoreload 10340 14368 Watching for file changes with StatReloader
INFO 2023-10-18 11:31:32,638 basehttp 10340 16548 "GET /orders_products/1/3/ HTTP/1.1" 200 630
INFO 2023-10-18 11:31:32,860 autoreload 10340 14368 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 11:31:33,987 autoreload 11628 15964 Watching for file changes with StatReloader
INFO 2023-10-18 11:35:02,722 autoreload 11628 15964 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 11:35:04,220 autoreload 15580 6192 Watching for file changes with StatReloader
INFO 2023-10-18 11:35:25,658 autoreload 15580 6192 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 11:35:26,791 autoreload 2600 9736 Watching for file changes with StatReloader
WARNING 2023-10-18 11:35:27,283 log 2600 6756 Not Found: /orders_products/1/3/
WARNING 2023-10-18 11:35:27,284 basehttp 2600 6756 "GET /orders_products/1/3/ HTTP/1.1" 404 2854
WARNING 2023-10-18 11:35:28,326 log 2600 6756 Not Found: /orders_products/1/3/
WARNING 2023-10-18 11:35:28,327 basehttp 2600 6756 "GET /orders_products/1/3/ HTTP/1.1" 404 2854
INFO 2023-10-18 11:35:47,146 autoreload 2600 9736 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 11:35:48,271 autoreload 13376 16592 Watching for file changes with StatReloader
WARNING 2023-10-18 11:35:48,486 log 13376 15492 Not Found: /orders_products/1/3/
WARNING 2023-10-18 11:35:48,487 basehttp 13376 15492 "GET /orders_products/1/3/ HTTP/1.1" 404 2854
WARNING 2023-10-18 11:35:49,566 log 13376 15492 Not Found: /orders_products/1/3/
WARNING 2023-10-18 11:35:49,566 basehttp 13376 15492 "GET /orders_products/1/3/ HTTP/1.1" 404 2854
WARNING 2023-10-18 11:36:03,662 log 13376 15492 Not Found: /orders_products/1/3/
WARNING 2023-10-18 11:36:03,662 basehttp 13376 15492 "GET /orders_products/1/3/ HTTP/1.1" 404 2854
WARNING 2023-10-18 11:36:06,186 log 13376 15492 Not Found: /orders_products/1/3/
WARNING 2023-10-18 11:36:06,187 basehttp 13376 15492 "GET /orders_products/1/3/ HTTP/1.1" 404 2854
WARNING 2023-10-18 11:36:06,735 log 13376 15492 Not Found: /orders_products/1/3/
WARNING 2023-10-18 11:36:06,735 basehttp 13376 15492 "GET /orders_products/1/3/ HTTP/1.1" 404 2854
WARNING 2023-10-18 11:36:08,280 log 13376 15492 Not Found: /orders_products/1/3/
WARNING 2023-10-18 11:36:08,281 basehttp 13376 15492 "GET /orders_products/1/3/ HTTP/1.1" 404 2854
WARNING 2023-10-18 11:36:40,151 log 13376 15492 Not Found: /orders_products/1/3/
WARNING 2023-10-18 11:36:40,151 basehttp 13376 15492 "GET /orders_products/1/3/ HTTP/1.1" 404 2854
INFO 2023-10-18 11:36:40,455 autoreload 13376 16592 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 11:36:41,601 autoreload 7552 3100 Watching for file changes with StatReloader
WARNING 2023-10-18 11:36:41,809 log 7552 9688 Not Found: /orders_products/1/3/
WARNING 2023-10-18 11:36:41,810 basehttp 7552 9688 "GET /orders_products/1/3/ HTTP/1.1" 404 2854
WARNING 2023-10-18 11:36:42,610 log 7552 9688 Not Found: /orders_products/1/3/
WARNING 2023-10-18 11:36:42,611 basehttp 7552 9688 "GET /orders_products/1/3/ HTTP/1.1" 404 2854
WARNING 2023-10-18 11:36:43,574 log 7552 9688 Not Found: /orders_products/1/3/
WARNING 2023-10-18 11:36:43,575 basehttp 7552 9688 "GET /orders_products/1/3/ HTTP/1.1" 404 2854
INFO 2023-10-18 11:38:03,760 autoreload 7552 3100 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 11:38:05,314 autoreload 16560 16700 Watching for file changes with StatReloader
INFO 2023-10-18 11:38:30,947 autoreload 16560 16700 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 11:38:32,356 autoreload 16552 5620 Watching for file changes with StatReloader
INFO 2023-10-18 11:38:32,484 basehttp 16552 15404 "GET /orders_products/1/3/ HTTP/1.1" 200 248
INFO 2023-10-18 11:38:39,093 autoreload 16552 5620 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 11:38:40,287 autoreload 15276 17188 Watching for file changes with StatReloader
INFO 2023-10-18 11:38:43,235 basehttp 15276 2444 "GET /orders_products/1/3/ HTTP/1.1" 200 630
INFO 2023-10-18 11:39:32,250 basehttp 15276 2444 "GET /orders_products/1/3/ HTTP/1.1" 200 617
INFO 2023-10-18 11:39:57,850 basehttp 15276 2444 "GET /orders_products/1/3/ HTTP/1.1" 200 603
INFO 2023-10-18 11:40:56,417 basehttp 15276 2444 "GET /orders_products/1/3/ HTTP/1.1" 200 603
INFO 2023-10-18 11:40:57,134 basehttp 15276 2444 "GET /orders_products/1/3/ HTTP/1.1" 200 603
INFO 2023-10-18 11:41:02,441 basehttp 15276 2444 "GET /orders_products/1/3/ HTTP/1.1" 200 617
INFO 2023-10-18 11:41:46,336 autoreload 16548 13988 Watching for file changes with StatReloader
INFO 2023-10-18 11:42:17,083 basehttp 16548 2604 "GET /orders_products/1/3/ HTTP/1.1" 200 599
INFO 2023-10-18 11:42:18,917 basehttp 16548 2604 "GET /orders_products/1/3/ HTTP/1.1" 200 599
INFO 2023-10-18 11:42:30,272 basehttp 16548 2604 "GET /orders_products/1/3/ HTTP/1.1" 200 599
INFO 2023-10-18 11:42:30,866 basehttp 16548 2604 "GET /orders_products/1/3/ HTTP/1.1" 200 599
INFO 2023-10-18 11:42:31,328 basehttp 16548 2604 "GET /orders_products/1/3/ HTTP/1.1" 200 599
INFO 2023-10-18 11:42:41,973 basehttp 16548 2604 "GET /orders_products/1/3/ HTTP/1.1" 200 599
INFO 2023-10-18 11:42:46,562 basehttp 16548 2604 "GET /orders_products/1/3/ HTTP/1.1" 200 603
INFO 2023-10-18 11:42:53,344 basehttp 16548 2604 "GET /orders_products/1/3/ HTTP/1.1" 200 599
INFO 2023-10-18 11:42:53,989 basehttp 16548 2604 "GET /orders_products/1/3/ HTTP/1.1" 200 599
INFO 2023-10-18 11:42:59,494 basehttp 16548 2604 "GET /orders_products/1/3/ HTTP/1.1" 200 599
INFO 2023-10-18 11:51:59,064 basehttp 16548 17000 "GET /orders_products/1/3/ HTTP/1.1" 200 599
INFO 2023-10-18 11:51:59,616 basehttp 16548 17000 "GET /orders_products/1/3/ HTTP/1.1" 200 599
INFO 2023-10-18 11:52:00,991 basehttp 16548 17000 "GET /orders_products/1/3/ HTTP/1.1" 200 599
INFO 2023-10-18 11:52:08,445 basehttp 16548 17000 "GET /orders_products/1/3/ HTTP/1.1" 200 599
INFO 2023-10-18 11:52:13,632 basehttp 16548 17000 "GET /orders_products/1/3/ HTTP/1.1" 200 617
INFO 2023-10-18 12:02:57,299 autoreload 1132 11676 Watching for file changes with StatReloader
INFO 2023-10-18 12:03:02,133 basehttp 1132 16400 "GET / HTTP/1.1" 200 125
WARNING 2023-10-18 12:03:26,909 log 1132 16400 Not Found: /orders_product/
WARNING 2023-10-18 12:03:26,910 basehttp 1132 16400 "GET /orders_product/ HTTP/1.1" 404 2675
WARNING 2023-10-18 12:03:53,320 log 1132 16400 Not Found: /orders_product
WARNING 2023-10-18 12:03:53,321 basehttp 1132 16400 "GET /orders_product HTTP/1.1" 404 2672
INFO 2023-10-18 12:04:30,517 autoreload 1132 11676 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\urls.py changed, reloading.
INFO 2023-10-18 12:04:31,712 autoreload 16076 14388 Watching for file changes with StatReloader
WARNING 2023-10-18 12:04:33,806 log 16076 16276 Not Found: /orders_product/2
WARNING 2023-10-18 12:04:33,807 basehttp 16076 16276 "GET /orders_product/2 HTTP/1.1" 404 2660
INFO 2023-10-18 12:04:41,197 basehttp 16076 16276 "GET /orders_products/2 HTTP/1.1" 301 0
INFO 2023-10-18 12:04:41,210 basehttp 16076 16276 "GET /orders_products/2/ HTTP/1.1" 200 834
INFO 2023-10-18 12:05:41,749 basehttp 16076 16276 "GET /orders_products/2/ HTTP/1.1" 200 806
ERROR 2023-10-18 12:07:43,067 log 16076 16276 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '()' from 'order_product.products.get()'
ERROR 2023-10-18 12:07:43,071 basehttp 16076 16276 "GET /orders_products/2/ HTTP/1.1" 500 147758
INFO 2023-10-18 12:08:37,287 basehttp 16076 16276 "GET /orders_products/2/ HTTP/1.1" 200 798
INFO 2023-10-18 12:08:38,352 basehttp 16076 16276 "GET /orders_products/2/ HTTP/1.1" 200 798
INFO 2023-10-18 12:08:45,677 basehttp 16076 16276 "GET /orders_products/2/ HTTP/1.1" 200 798
INFO 2023-10-18 12:08:48,692 basehttp 16076 16276 "GET /orders_products/2/ HTTP/1.1" 200 798
INFO 2023-10-18 12:08:49,213 basehttp 16076 16276 "GET /orders_products/2/ HTTP/1.1" 200 798
ERROR 2023-10-18 12:08:57,704 log 16076 16276 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '([product])' from 'order_product.products.get([product])'
ERROR 2023-10-18 12:08:57,710 basehttp 16076 16276 "GET /orders_products/2/ HTTP/1.1" 500 147920
INFO 2023-10-18 12:09:31,703 basehttp 16076 16276 "GET /orders_products/2/ HTTP/1.1" 200 834
INFO 2023-10-18 12:10:00,553 autoreload 16076 14388 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:10:01,973 autoreload 8052 15460 Watching for file changes with StatReloader
ERROR 2023-10-18 12:10:02,199 log 8052 12604 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 46, in get_context_data
    print(order_products.products)
AttributeError: 'QuerySet' object has no attribute 'products'
ERROR 2023-10-18 12:10:02,201 basehttp 8052 12604 "GET /orders_products/2/ HTTP/1.1" 500 80961
INFO 2023-10-18 12:10:13,969 autoreload 8052 15460 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:10:15,316 autoreload 9784 16940 Watching for file changes with StatReloader
INFO 2023-10-18 12:10:16,441 basehttp 9784 17384 "GET /orders_products/2/ HTTP/1.1" 200 834
INFO 2023-10-18 12:10:33,577 autoreload 9784 16940 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:10:35,153 autoreload 4044 1852 Watching for file changes with StatReloader
INFO 2023-10-18 12:11:03,250 autoreload 4044 1852 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:11:04,685 autoreload 13872 15580 Watching for file changes with StatReloader
ERROR 2023-10-18 12:11:05,649 log 13872 16584 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 46, in get_context_data
    print(order_products.client)
AttributeError: 'QuerySet' object has no attribute 'client'
ERROR 2023-10-18 12:11:05,651 basehttp 13872 16584 "GET /orders_products/2/ HTTP/1.1" 500 81417
INFO 2023-10-18 12:11:32,371 autoreload 13872 15580 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:11:33,757 autoreload 16876 16748 Watching for file changes with StatReloader
INFO 2023-10-18 12:11:33,938 basehttp 16876 17088 "GET /orders_products/2/ HTTP/1.1" 200 834
WARNING 2023-10-18 12:19:42,881 log 16876 6192 Not Found: /orders_products/1/3/
WARNING 2023-10-18 12:19:42,882 basehttp 16876 6192 "GET /orders_products/1/3/ HTTP/1.1" 404 2672
INFO 2023-10-18 12:19:44,716 autoreload 16876 16748 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\models.py changed, reloading.
INFO 2023-10-18 12:19:46,068 autoreload 4032 14204 Watching for file changes with StatReloader
WARNING 2023-10-18 12:19:47,718 log 4032 3716 Not Found: /orders_products/1/3/
WARNING 2023-10-18 12:19:47,719 basehttp 4032 3716 "GET /orders_products/1/3/ HTTP/1.1" 404 2672
ERROR 2023-10-18 12:19:52,851 log 4032 3716 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '()' from 'order_product.products.all()'
ERROR 2023-10-18 12:19:52,855 basehttp 4032 3716 "GET /orders_products/2/ HTTP/1.1" 500 147758
INFO 2023-10-18 12:20:04,391 basehttp 4032 3716 "GET /orders_products/2/ HTTP/1.1" 200 906
INFO 2023-10-18 12:22:21,479 autoreload 4032 14204 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\models.py changed, reloading.
INFO 2023-10-18 12:22:23,073 autoreload 15732 5084 Watching for file changes with StatReloader
INFO 2023-10-18 12:23:32,738 autoreload 15732 5084 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:23:34,041 autoreload 4364 15688 Watching for file changes with StatReloader
ERROR 2023-10-18 12:23:34,451 log 4364 16192 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 45, in get_context_data
    order = Order.objects.get(client_id=client_id)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
myapp.models.Order.MultipleObjectsReturned: get() returned more than one Order -- it returned 2!
ERROR 2023-10-18 12:23:34,455 basehttp 4364 16192 "GET /orders_products/2/ HTTP/1.1" 500 90198
ERROR 2023-10-18 12:23:36,035 log 4364 16192 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 45, in get_context_data
    order = Order.objects.get(client_id=client_id)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
myapp.models.Order.MultipleObjectsReturned: get() returned more than one Order -- it returned 2!
ERROR 2023-10-18 12:23:36,038 basehttp 4364 16192 "GET /orders_products/2/ HTTP/1.1" 500 90198
INFO 2023-10-18 12:23:51,605 autoreload 4364 15688 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:23:52,972 autoreload 15684 14236 Watching for file changes with StatReloader
ERROR 2023-10-18 12:23:53,401 log 15684 17180 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 45, in get_context_data
    order = Order.objects.get(client_id=client_id)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
myapp.models.Order.MultipleObjectsReturned: get() returned more than one Order -- it returned 2!
ERROR 2023-10-18 12:23:53,404 basehttp 15684 17180 "GET /orders_products/2/ HTTP/1.1" 500 90198
ERROR 2023-10-18 12:23:55,284 log 15684 17180 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 45, in get_context_data
    order = Order.objects.get(client_id=client_id)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
myapp.models.Order.MultipleObjectsReturned: get() returned more than one Order -- it returned 2!
ERROR 2023-10-18 12:23:55,286 basehttp 15684 17180 "GET /orders_products/2/ HTTP/1.1" 500 90198
ERROR 2023-10-18 12:27:53,597 log 15684 17180 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 45, in get_context_data
    order = Order.objects.get(client_id=client_id)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
myapp.models.Order.MultipleObjectsReturned: get() returned more than one Order -- it returned 2!
ERROR 2023-10-18 12:27:53,599 basehttp 15684 17180 "GET /orders_products/2/ HTTP/1.1" 500 90198
INFO 2023-10-18 12:28:31,834 autoreload 15684 14236 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:28:33,390 autoreload 16960 1132 Watching for file changes with StatReloader
INFO 2023-10-18 12:28:34,248 basehttp 16960 12120 "GET /orders_products/2/ HTTP/1.1" 200 906
INFO 2023-10-18 12:29:36,697 autoreload 16960 1132 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:29:38,094 autoreload 15508 2116 Watching for file changes with StatReloader
INFO 2023-10-18 12:29:43,158 basehttp 15508 11408 "GET /orders_products/2/ HTTP/1.1" 200 798
INFO 2023-10-18 12:29:48,509 basehttp 15508 11408 "GET /orders_products/2/ HTTP/1.1" 200 906
ERROR 2023-10-18 12:30:06,645 log 15508 11408 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'order_product.products.all[0]'
ERROR 2023-10-18 12:30:06,649 basehttp 15508 11408 "GET /orders_products/2/ HTTP/1.1" 500 147776
ERROR 2023-10-18 12:30:08,009 log 15508 11408 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'order_product.products.all[0]'
ERROR 2023-10-18 12:30:08,013 basehttp 15508 11408 "GET /orders_products/2/ HTTP/1.1" 500 147776
ERROR 2023-10-18 12:30:14,186 log 15508 11408 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0].name' from 'order_product.products.all[0].name'
ERROR 2023-10-18 12:30:14,191 basehttp 15508 11408 "GET /orders_products/2/ HTTP/1.1" 500 147866
ERROR 2023-10-18 12:30:20,970 log 15508 11408 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'order_product.products.all[0]'
ERROR 2023-10-18 12:30:20,974 basehttp 15508 11408 "GET /orders_products/2/ HTTP/1.1" 500 147776
ERROR 2023-10-18 12:30:22,179 log 15508 11408 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\defaulttags.py", line 814, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0]' from 'order_product.products.all[0]'
ERROR 2023-10-18 12:30:22,183 basehttp 15508 11408 "GET /orders_products/2/ HTTP/1.1" 500 147776
INFO 2023-10-18 12:30:26,551 basehttp 15508 11408 "GET /orders_products/2/ HTTP/1.1" 200 906
INFO 2023-10-18 12:32:02,704 basehttp 15508 11408 "GET /orders_products/2/ HTTP/1.1" 200 809
INFO 2023-10-18 12:33:11,250 autoreload 1844 17276 Watching for file changes with StatReloader
INFO 2023-10-18 12:33:11,533 basehttp 1844 17348 "GET /orders_products/2/ HTTP/1.1" 200 1013
INFO 2023-10-18 12:36:04,487 autoreload 1844 17276 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\models.py changed, reloading.
INFO 2023-10-18 12:36:06,313 autoreload 2264 15252 Watching for file changes with StatReloader
INFO 2023-10-18 12:36:21,640 autoreload 2264 15252 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:36:22,769 autoreload 2900 5500 Watching for file changes with StatReloader
ERROR 2023-10-18 12:36:24,428 log 2900 4932 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 45, in get_context_data
    order = Order.objects.get(client_id=client_id)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
myapp.models.Order.MultipleObjectsReturned: get() returned more than one Order -- it returned 2!
ERROR 2023-10-18 12:36:24,431 basehttp 2900 4932 "GET /orders_products/2/ HTTP/1.1" 500 90279
INFO 2023-10-18 12:36:47,825 autoreload 2900 5500 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:36:49,430 autoreload 15760 1620 Watching for file changes with StatReloader
INFO 2023-10-18 12:36:54,145 autoreload 15760 1620 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:36:55,601 autoreload 952 11108 Watching for file changes with StatReloader
INFO 2023-10-18 12:36:55,818 basehttp 952 6680 "GET /orders_products/2/ HTTP/1.1" 200 1013
INFO 2023-10-18 12:36:58,960 basehttp 952 6680 "GET /orders_products/2/ HTTP/1.1" 200 1013
INFO 2023-10-18 12:37:00,688 basehttp 952 6680 "GET /orders_products/2/ HTTP/1.1" 200 1013
INFO 2023-10-18 12:37:47,383 autoreload 952 11108 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:37:48,653 autoreload 12452 16940 Watching for file changes with StatReloader
ERROR 2023-10-18 12:37:49,597 log 12452 15104 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 46, in get_context_data
    context["orders"] = orders
NameError: name 'orders' is not defined
ERROR 2023-10-18 12:37:49,599 basehttp 12452 15104 "GET /orders_products/2/ HTTP/1.1" 500 81400
ERROR 2023-10-18 12:37:50,920 log 12452 15104 Internal Server Error: /orders_products/2/
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 46, in get_context_data
    context["orders"] = orders
NameError: name 'orders' is not defined
ERROR 2023-10-18 12:37:50,922 basehttp 12452 15104 "GET /orders_products/2/ HTTP/1.1" 500 81400
INFO 2023-10-18 12:37:57,484 autoreload 12452 16940 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:37:58,814 autoreload 11404 15732 Watching for file changes with StatReloader
INFO 2023-10-18 12:37:59,125 basehttp 11404 7396 "GET /orders_products/2/ HTTP/1.1" 200 809
INFO 2023-10-18 12:38:05,241 basehttp 11404 7396 "GET /orders_products/1/ HTTP/1.1" 200 401
INFO 2023-10-18 12:38:08,782 basehttp 11404 7396 "GET /orders_products/3/ HTTP/1.1" 200 605
INFO 2023-10-18 12:38:43,254 autoreload 11404 15732 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:38:44,735 autoreload 11376 12680 Watching for file changes with StatReloader
INFO 2023-10-18 12:41:39,901 autoreload 11376 12680 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:41:41,362 autoreload 16992 10892 Watching for file changes with StatReloader
INFO 2023-10-18 12:42:04,488 autoreload 16992 10892 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\urls.py changed, reloading.
INFO 2023-10-18 12:42:05,773 autoreload 16220 8224 Watching for file changes with StatReloader
INFO 2023-10-18 12:42:06,031 basehttp 16220 17104 "GET /orders_products/3/ HTTP/1.1" 200 466
INFO 2023-10-18 12:43:16,602 autoreload 16220 8224 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\urls.py changed, reloading.
INFO 2023-10-18 12:43:17,777 autoreload 10136 13892 Watching for file changes with StatReloader
INFO 2023-10-18 12:43:18,596 basehttp 10136 4460 "GET /orders_products/3/7 HTTP/1.1" 200 485
INFO 2023-10-18 12:43:21,787 basehttp 10136 4460 "GET /orders_products/3/10 HTTP/1.1" 200 486
INFO 2023-10-18 12:43:57,284 basehttp 10136 4460 "GET /orders_products/3/10 HTTP/1.1" 200 826
INFO 2023-10-18 12:47:05,381 autoreload 10136 13892 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:47:06,837 autoreload 9660 11168 Watching for file changes with StatReloader
INFO 2023-10-18 12:47:43,494 autoreload 9660 11168 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:47:44,934 autoreload 5712 14492 Watching for file changes with StatReloader
ERROR 2023-10-18 12:47:50,542 log 5712 12476 Internal Server Error: /orders_products/2/10
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 45, in get_context_data
    end_date = datetime.now()
AttributeError: module 'datetime' has no attribute 'now'
ERROR 2023-10-18 12:47:50,544 basehttp 5712 12476 "GET /orders_products/2/10 HTTP/1.1" 500 80852
ERROR 2023-10-18 12:47:54,606 log 5712 12476 Internal Server Error: /orders_products/3/10
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 45, in get_context_data
    end_date = datetime.now()
AttributeError: module 'datetime' has no attribute 'now'
ERROR 2023-10-18 12:47:54,609 basehttp 5712 12476 "GET /orders_products/3/10 HTTP/1.1" 500 80852
INFO 2023-10-18 12:48:09,955 autoreload 5712 14492 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:48:11,511 autoreload 16436 16500 Watching for file changes with StatReloader
INFO 2023-10-18 12:48:12,259 basehttp 16436 13224 "GET /orders_products/3/10 HTTP/1.1" 200 826
INFO 2023-10-18 12:48:15,867 basehttp 16436 13224 "GET /orders_products/2/10 HTTP/1.1" 200 1674
INFO 2023-10-18 12:48:50,032 basehttp 16436 13224 "GET /orders_products/2/1 HTTP/1.1" 200 825
INFO 2023-10-18 12:48:52,974 basehttp 16436 13224 "GET /orders_products/2/2 HTTP/1.1" 200 1673
INFO 2023-10-18 12:48:55,024 basehttp 16436 13224 "GET /orders_products/2/1 HTTP/1.1" 200 825
INFO 2023-10-18 12:48:57,089 basehttp 16436 13224 "GET /orders_products/2/2 HTTP/1.1" 200 1673
INFO 2023-10-18 12:50:21,761 basehttp 16436 13224 "GET /orders_products/2/2 HTTP/1.1" 200 1673
INFO 2023-10-18 12:50:23,159 basehttp 16436 13224 "GET /orders_products/2/2 HTTP/1.1" 200 1673
INFO 2023-10-18 12:50:23,543 autoreload 16436 16500 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:50:24,896 autoreload 17140 14832 Watching for file changes with StatReloader
INFO 2023-10-18 12:50:25,071 basehttp 17140 10396 "GET /orders_products/2/2 HTTP/1.1" 200 1673
INFO 2023-10-18 12:50:27,070 basehttp 17140 10396 "GET /orders_products/2/2 HTTP/1.1" 200 1673
INFO 2023-10-18 12:50:42,159 autoreload 17140 14832 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:50:43,604 autoreload 2264 5660 Watching for file changes with StatReloader
INFO 2023-10-18 12:51:24,879 autoreload 2264 5660 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:51:26,284 autoreload 15940 16484 Watching for file changes with StatReloader
ERROR 2023-10-18 12:51:26,577 log 15940 13996 Internal Server Error: /orders_products/2/2
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 47, in get_context_data
    orders = Order.objects.filter(client_id=client_id, order_date__ge=start_date).order_by('-id')
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1185, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1224, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'ge' for DateField or join on the field not permitted, perhaps you meant gte?
ERROR 2023-10-18 12:51:26,582 basehttp 15940 13996 "GET /orders_products/2/2 HTTP/1.1" 500 128713
ERROR 2023-10-18 12:51:28,620 log 15940 13996 Internal Server Error: /orders_products/2/2
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 47, in get_context_data
    orders = Order.objects.filter(client_id=client_id, order_date__ge=start_date).order_by('-id')
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1345, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1185, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\db\models\sql\query.py", line 1224, in try_transform
    raise FieldError(
django.core.exceptions.FieldError: Unsupported lookup 'ge' for DateField or join on the field not permitted, perhaps you meant gte?
ERROR 2023-10-18 12:51:28,623 basehttp 15940 13996 "GET /orders_products/2/2 HTTP/1.1" 500 128713
INFO 2023-10-18 12:51:32,057 autoreload 15940 16484 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:51:33,204 autoreload 15928 14740 Watching for file changes with StatReloader
INFO 2023-10-18 12:52:35,281 autoreload 15928 14740 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:52:36,668 autoreload 15720 16936 Watching for file changes with StatReloader
INFO 2023-10-18 12:52:36,942 basehttp 15720 11708 "GET /orders_products/2/2 HTTP/1.1" 200 825
INFO 2023-10-18 12:52:44,324 basehttp 15720 11708 "GET /orders_products/2/1 HTTP/1.1" 200 825
INFO 2023-10-18 12:52:48,411 basehttp 15720 11708 "GET /orders_products/2/10 HTTP/1.1" 200 1674
INFO 2023-10-18 12:52:56,989 autoreload 15720 16936 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:52:58,115 autoreload 6552 476 Watching for file changes with StatReloader
INFO 2023-10-18 12:52:58,294 basehttp 6552 14864 "GET /orders_products/2/10 HTTP/1.1" 200 1674
INFO 2023-10-18 12:54:04,505 autoreload 6552 476 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 12:54:05,675 autoreload 13680 16988 Watching for file changes with StatReloader
INFO 2023-10-18 12:54:07,266 basehttp 13680 16016 "GET /orders_products/2/10 HTTP/1.1" 200 1674
INFO 2023-10-18 12:54:09,689 basehttp 13680 16016 "GET /orders_products/2/10 HTTP/1.1" 200 1674
INFO 2023-10-18 12:54:10,363 basehttp 13680 16016 "GET /orders_products/2/10 HTTP/1.1" 200 1674
INFO 2023-10-18 12:54:10,811 basehttp 13680 16016 "GET /orders_products/2/10 HTTP/1.1" 200 1674
INFO 2023-10-18 12:54:11,204 basehttp 13680 16016 "GET /orders_products/2/10 HTTP/1.1" 200 1674
INFO 2023-10-18 12:54:11,381 basehttp 13680 16016 "GET /orders_products/2/10 HTTP/1.1" 200 1674
INFO 2023-10-18 12:54:14,095 basehttp 13680 16016 "GET /orders_products/2/10 HTTP/1.1" 200 1674
INFO 2023-10-18 12:54:14,707 basehttp 13680 16016 "GET /orders_products/2/10 HTTP/1.1" 200 1674
INFO 2023-10-18 12:57:31,331 basehttp 13680 16016 "GET /orders_products/2/10 HTTP/1.1" 200 888
INFO 2023-10-18 13:06:35,851 autoreload 13680 16988 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 13:06:37,116 autoreload 16572 4044 Watching for file changes with StatReloader
INFO 2023-10-18 13:08:50,512 autoreload 16572 4044 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 13:08:52,347 autoreload 12784 932 Watching for file changes with StatReloader
INFO 2023-10-18 13:09:34,612 autoreload 15940 3392 Watching for file changes with StatReloader
INFO 2023-10-18 13:28:01,428 autoreload 17296 1152 Watching for file changes with StatReloader
INFO 2023-10-18 13:28:18,875 autoreload 17296 1152 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 13:28:20,321 autoreload 14348 5928 Watching for file changes with StatReloader
INFO 2023-10-18 13:31:31,588 autoreload 16768 16444 Watching for file changes with StatReloader
INFO 2023-10-18 13:32:47,924 autoreload 9348 16480 Watching for file changes with StatReloader
INFO 2023-10-18 13:32:48,270 basehttp 9348 14824 "GET /orders_products/47/5 HTTP/1.1" 200 749
INFO 2023-10-18 13:32:50,750 basehttp 9348 14824 "GET /orders_products/47/1 HTTP/1.1" 200 749
INFO 2023-10-18 13:32:53,010 basehttp 9348 14824 "GET /orders_products/47/2 HTTP/1.1" 200 749
INFO 2023-10-18 13:32:56,598 basehttp 9348 14824 "GET /orders_products/47/10 HTTP/1.1" 200 916
INFO 2023-10-18 13:32:59,582 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1255
INFO 2023-10-18 13:33:30,063 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1238
INFO 2023-10-18 13:33:31,995 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1238
INFO 2023-10-18 13:33:41,122 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1238
ERROR 2023-10-18 13:34:13,187 log 9348 14824 Internal Server Error: /orders_products/47/40
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0].order.client.name' from 'orders[0].order.client.name'
ERROR 2023-10-18 13:34:13,195 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 500 161314
ERROR 2023-10-18 13:34:14,944 log 9348 14824 Internal Server Error: /orders_products/47/40
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 449, in parse
    raise self.error(token, e)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[0].order.client.name' from 'orders[0].order.client.name'
ERROR 2023-10-18 13:34:14,948 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 500 161314
INFO 2023-10-18 13:34:26,044 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1238
INFO 2023-10-18 13:34:27,270 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1238
INFO 2023-10-18 13:34:27,755 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1238
INFO 2023-10-18 13:34:33,164 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1238
INFO 2023-10-18 13:34:33,867 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1238
INFO 2023-10-18 13:34:37,739 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1395
INFO 2023-10-18 13:34:43,993 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1256
INFO 2023-10-18 13:34:53,739 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1238
INFO 2023-10-18 13:35:02,025 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1238
INFO 2023-10-18 13:35:09,632 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1256
INFO 2023-10-18 13:35:19,068 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1256
INFO 2023-10-18 13:35:27,503 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1254
INFO 2023-10-18 13:35:31,993 basehttp 9348 14824 "GET /orders_products/47/40 HTTP/1.1" 200 1254
INFO 2023-10-18 13:35:41,586 basehttp 9348 14824 "GET /orders_products/169/40 HTTP/1.1" 200 740
INFO 2023-10-18 13:35:44,121 basehttp 9348 14824 "GET /orders_products/169/1 HTTP/1.1" 200 566
INFO 2023-10-18 13:35:46,572 basehttp 9348 14824 "GET /orders_products/169/100 HTTP/1.1" 200 903
INFO 2023-10-18 13:35:48,825 basehttp 9348 14824 "GET /orders_products/169/10000 HTTP/1.1" 200 1865
INFO 2023-10-18 13:35:51,379 basehttp 9348 14824 "GET /orders_products/169/100000 HTTP/1.1" 200 1866
ERROR 2023-10-18 13:35:55,247 log 9348 14824 Internal Server Error: /orders_products/169/1000000000000000
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\views\generic\base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 46, in get_context_data
    start_date= end_date - timedelta(days=kwargs["days"])
OverflowError: Python int too large to convert to C int
ERROR 2023-10-18 13:35:55,249 basehttp 9348 14824 "GET /orders_products/169/1000000000000000 HTTP/1.1" 500 81135
INFO 2023-10-18 13:35:58,052 basehttp 9348 14824 "GET /orders_products/169/10000 HTTP/1.1" 200 1865
INFO 2023-10-18 13:44:16,135 autoreload 9348 16480 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\urls.py changed, reloading.
INFO 2023-10-18 13:44:17,275 autoreload 9876 14536 Watching for file changes with StatReloader
INFO 2023-10-18 13:44:18,420 basehttp 9876 16784 "GET / HTTP/1.1" 200 125
INFO 2023-10-18 13:46:14,341 basehttp 9876 16784 "GET / HTTP/1.1" 200 125
INFO 2023-10-18 13:46:16,003 basehttp 9876 16784 "GET / HTTP/1.1" 200 125
INFO 2023-10-18 13:46:16,233 autoreload 9876 14536 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 13:46:17,516 autoreload 17356 10992 Watching for file changes with StatReloader
ERROR 2023-10-18 13:46:18,372 log 17356 14600 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 15, in index
    return render(request,"myapp3/index.html")
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/index.html
ERROR 2023-10-18 13:46:18,376 basehttp 17356 14600 "GET / HTTP/1.1" 500 80762
ERROR 2023-10-18 13:46:19,505 log 17356 14600 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 15, in index
    return render(request,"myapp3/index.html")
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/index.html
ERROR 2023-10-18 13:46:19,507 basehttp 17356 14600 "GET / HTTP/1.1" 500 80762
INFO 2023-10-18 13:46:24,358 autoreload 17356 10992 K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py changed, reloading.
INFO 2023-10-18 13:46:25,498 autoreload 2264 15228 Watching for file changes with StatReloader
ERROR 2023-10-18 13:46:26,450 log 2264 14824 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 15, in index
    return render(request,"myapp/index.html")
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-10-18 13:46:26,454 basehttp 2264 14824 "GET / HTTP/1.1" 500 124124
ERROR 2023-10-18 13:46:27,365 log 2264 14824 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "K:\django_lessons_gb\home_work\hw_three\myproject\myapp\views.py", line 15, in index
    return render(request,"myapp/index.html")
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\UberCool\AppData\Local\Programs\Python\Python310\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2023-10-18 13:46:27,369 basehttp 2264 14824 "GET / HTTP/1.1" 500 124124
INFO 2023-10-18 13:46:41,761 basehttp 2264 14824 "GET / HTTP/1.1" 200 249
INFO 2023-10-18 13:46:42,800 basehttp 2264 14824 "GET / HTTP/1.1" 200 249
WARNING 2023-10-18 13:46:49,008 log 2264 14824 Not Found: /2/1
WARNING 2023-10-18 13:46:49,009 basehttp 2264 14824 "GET /2/1 HTTP/1.1" 404 2470
INFO 2023-10-18 13:46:55,414 basehttp 2264 14824 "GET /orders_products/2/1 HTTP/1.1" 200 722
INFO 2023-10-18 13:47:00,020 basehttp 2264 14824 "GET / HTTP/1.1" 200 249
